/*
 * exiv2-ifdid.h 
 *
 * Author(s):
 *	Stephane Delcroix  (stephane@delcroix.org)
 *
 * Copyright (c) 2008 Novell, Inc.
 *
 * 
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 * 
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 */

#include <exiv2/types.hpp>
//FIXME: this should be autogenerated from types.hpp

enum Exiv2IfdId { 
	ifdIdNotSet 	= Exiv2::ifdIdNotSet,
	ifd0Id		= Exiv2::ifd0Id, 
	exifIfdId	= Exiv2::exifIfdId, 
	gpsIfdId	= Exiv2::gpsIfdId, 
	iopIfdId	= Exiv2::iopIfdId, 
	ifd1Id		= Exiv2::ifd1Id, 
	ifd2Id		= Exiv2::ifd2Id,
	subImage1Id	= Exiv2::subImage1Id, 
	subImage2Id	= Exiv2::subImage2Id, 
	subImage3Id	= Exiv2::subImage3Id, 
	subImage4Id	= Exiv2::subImage4Id,
	canonIfdId	= Exiv2::canonIfdId, 
	canonCsIfdId	= Exiv2::canonCsIfdId, 
	canonSiIfdId	= Exiv2::canonSiIfdId, 
	canonCfIfdId	= Exiv2::canonCfIfdId,
	canonPiIfdId	= Exiv2::canonPiIfdId, 
	canonPaIfdId	= Exiv2::canonPaIfdId,
	fujiIfdId	= Exiv2::fujiIfdId,
	minoltaIfdId	= Exiv2::minoltaIfdId, 
	minoltaCs5DIfdId	= Exiv2::minoltaCs5DIfdId, 
	minoltaCs7DIfdId	= Exiv2::minoltaCs7DIfdId,
	minoltaCsOldIfdId	= Exiv2::minoltaCsOldIfdId, 
	minoltaCsNewIfdId	= Exiv2::minoltaCsNewIfdId,
	nikon1IfdId	= Exiv2::nikon1IfdId, 
	nikon2IfdId	= Exiv2::nikon2IfdId, 
	nikon3IfdId	= Exiv2::nikon3IfdId, 
	nikonPvIfdId	= Exiv2::nikonPvIfdId,
	olympusIfdId	= Exiv2::olympusIfdId, 
	panasonicIfdId	= Exiv2::panasonicIfdId, 
	pentaxIfdId	= Exiv2::pentaxIfdId, 
	sigmaIfdId	= Exiv2::sigmaIfdId, 
	sonyIfdId	= Exiv2::sonyIfdId,
	lastIfdId	= Exiv2::lastIfdId
};

